"""
agent.py - Core module for the Agentic AI Research & Report Generation System.

Purpose
-------
This module is the entry point for talking to the Gemini model. In this first
version it does only three things:

1. Loads the GEMINI_API_KEY from the project's root `.env` file.
2. Creates (and reuses) a single Gemini client.
3. Exposes `run_agent(task)`, which sends a task to Gemini and returns the
   response text.

Later versions will grow this into a full research agent that plans, researches,
analyses, and writes reports. For now there are no tools, no web search, and no
planning loops - just a clean foundation to build on.

Usage
-----
    from src.agent import run_agent

    answer = run_agent("Explain what a research agent is.")
    print(answer)
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from google import genai
from google.genai import errors as genai_errors
from google.genai import types

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# The project root is one level above the `src/` folder that contains this file.
PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = PROJECT_ROOT / ".env"

# Load variables from the root `.env` file into the process environment.
# If the file doesn't exist, this silently does nothing and we'll fall back to
# any variables already set in the environment.
load_dotenv(dotenv_path=ENV_PATH)

# Name of the Gemini model to use. Kept as a constant so it's easy to change.
MODEL_NAME = "gemini-3.5-flash-lite"

# Tells the model what role it plays. We'll expand this as the agent gains
# new abilities (planning, research, analysis, report generation).
SYSTEM_INSTRUCTION = (
    "You are an AI research agent. Your purpose is to help users investigate "
    "topics and produce well-structured reports. In future versions you will "
    "perform planning, research, analysis, and report generation. For now, "
    "respond to the user's task clearly, accurately, and concisely."
)

# Holds the shared client so we only create it once (see `get_client`).
_client: genai.Client | None = None


# ---------------------------------------------------------------------------
# Client setup
# ---------------------------------------------------------------------------

def get_client() -> genai.Client:
    """Return a reusable Gemini client, creating it on first use.

    The API key is read from the `GEMINI_API_KEY` environment variable
    (populated from the root `.env` file). The key is never printed or logged.

    Raises:
        EnvironmentError: If `GEMINI_API_KEY` is missing or empty.
    """
    global _client

    if _client is None:
        api_key = os.getenv("GEMINI_API_KEY")

        if not api_key or not api_key.strip():
            raise EnvironmentError(
                "GEMINI_API_KEY is not set. Add a line like "
                "GEMINI_API_KEY=your_key_here to the .env file in the project "
                f"root ({ENV_PATH}) and try again."
            )

        _client = genai.Client(api_key=api_key.strip())

    return _client


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run_agent(task: str) -> str:
    """Send a task to Gemini and return its response text.

    Args:
        task: The user's research request, as a non-empty string.

    Returns:
        The text generated by Gemini.

    Raises:
        ValueError: If `task` is not a string or is empty/whitespace only.
        EnvironmentError: If `GEMINI_API_KEY` is not configured.
        RuntimeError: If the Gemini API call fails or returns no text.
    """
    # 1. Validate the input.
    if not isinstance(task, str):
        raise ValueError("task must be a string.")
    if not task.strip():
        raise ValueError("task must be a non-empty string.")

    # 2. Get the shared client (raises a clear error if the key is missing).
    client = get_client()

    # 3. Call Gemini, converting API failures into a simple RuntimeError.
    try:
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=task.strip(),
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_INSTRUCTION,
            ),
        )
    except genai_errors.APIError as exc:
        raise RuntimeError(f"Gemini API request failed: {exc}") from exc
    except Exception as exc:  # e.g. network problems
        raise RuntimeError(
            f"Unexpected error while calling Gemini: {exc}"
        ) from exc

    # 4. Make sure we actually got text back (it can be empty if blocked).
    if not response.text:
        raise RuntimeError(
            "Gemini returned an empty response. The request may have been "
            "blocked or produced no text."
        )

    return response.text
    def run_research_workflow(topic: str) -> str:
    """
    Run the complete research workflow.

    Flow:
    1. Create a research plan.
    2. Research the planned tasks.
    3. Combine the research.
    4. Generate the final report.
    """

    if not isinstance(topic, str):
        raise ValueError("topic must be a string.")

    if not topic.strip():
        raise ValueError("topic must be a non-empty string.")

    from src.planner import create_research_plan
    from src.researcher import research_task
    from src.report_generator import generate_report

    clean_topic = topic.strip()

    # Step 1: Create the research plan
    plan = create_research_plan(clean_topic)

    # Step 2: Extract research tasks from the plan
    tasks = []

    for line in plan.splitlines():
        line = line.strip()

        if not line:
            continue

        # Skip headings and descriptive lines
        if line[0].isdigit() and "." in line:
            task = line.split(".", 1)[1].strip()

            if task:
                tasks.append(task)

    if not tasks:
        tasks = [plan]

    # Step 3: Research each task
    research_results = []

    for index, task in enumerate(tasks, start=1):
        research = research_task(task)

        research_results.append(
            f"Research Task {index}:\n"
            f"{task}\n\n"
            f"{research}"
        )

    combined_research = "\n\n".join(research_results)

    # Step 4: Generate the final report
    report = generate_report(
        clean_topic,
        combined_research
    )

    return report